### PR TITLE
Merge `staging` branch work, Switch from Prettier to Standard, clean up static asset uploader

### LINKED ISSUE #319: Update Lambda runtime to Node10
Currently Node8.x is used as runtime for the Lambda functions.

Node8.x will reach it's EOL at the end of 2019.
As of Janurary 6th, 2020 you will no longer be able to create Lambda functions with Node8.x runtime.
As of February 3, 2020 you will not be able to update existing Node8 functions.

(information taken from AWS notification mails)

### LINKED ISSUE #324: [staging] JS error after login
The staging branch is currently not working.
After logging in, there's a JS error about ne.get where .get is not defined (ne is a Promise)

Commit 2f30d2ac introduced some code in the file lambdas/static-asset-uploader/build/static/js/main.74ad274d.chunk.js which is simply wrong:

```js
return ne.get("/testLayer",{},{},{}).then(function(e){return console.log("testLayer success:",e)}).catch(function(e){return console.error("testLayer error:",e)}),
```

Rebuilding everything fixes the issue.

### PR DESCRIPTION
**Pull request by amazon-meaisiah**
*Issue #, if available:*

*Description of changes:*

- I took `staging`, rebased off of master, reconciled their differences (like Node versions), and fixed a scrolling bug in it.
- I added a `LocalDevelopmentMode` to unblock my own personal development as per #344, to resolve CORS issues I was dealing with.
- I switched from Prettier to Standard for a much easier development experience, and fixed resulting errors throughout. I also cleaned up a couple places for style, mainly to use async functions and to avoid a few related anti-patterns.
- I removed a few heavy, unnecessary dependencies from the static asset uploader and cleaned up the general implementation a bit.
- I rebuilt everything with the new changes

Closes #319 
Closes #324 (I *believe*)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lambdas/common-layer/nodejs/node_modules/dev-portal-common/notify-cfn.js [hunk 1]
```diff
@@ -100,7 +100,7 @@ function ofSuccess (config) { return notifyCFN({ ...config, responseStatus: 'SUC
...
 function ofFailure (config) { return notifyCFN({ ...config, responseStatus: 'FAILED' }) }
 
-notifyCFN.ofSuccess = ofSuccess
-notifyCFN.ofFailure = ofFailure
-
-module.exports = notifyCFN
+module.exports = {
+  ofSuccess,
+  ofFailure
+}
```
Comment (MynockSpit) [inline lambdas/common-layer/nodejs/node_modules/dev-portal-common/notify-cfn.js]: Was there anything that used the raw `notifyCFN`?

File: lambdas/listener/index.js [hunk 2]
```diff
@@ -17,62 +16,58 @@ exports.handler = (event, context, callback) => {
...
+      controller.getUsagePlanForProductCode(customerId, reject, resolve)
     })
-  })
-}
-
-function unsubscribe (customerId, productCode, callback) {
-  console.log(`Unsubscribing customer ${customerId} from product code ${productCode}`)
 
-  function err (err) {
+    return await new Promise((resolve, reject) => {
```
Comment (MynockSpit) [inline lambdas/listener/index.js]: Why `return await`?

File: lambdas/static-asset-uploader/index.js [hunk 3]
```diff
@@ -191,55 +105,99 @@ function createCatalogDirectory (staticBucketName) {
...
-  const configObject = {
-    restApiId: event.ResourceProperties.RestApiId,
-    region: event.ResourceProperties.Region,
-    identityPoolId: event.ResourceProperties.IdentityPoolId,
-    userPoolId: event.ResourceProperties.UserPoolId,
-    userPoolClientId: event.ResourceProperties.UserPoolClientId,
-    userPoolDomain: event.ResourceProperties.UserPoolDomain,
-    // this is a stringified boolean here; let's go ahead and make it a real boolean
-    feedbackEnabled: event.ResourceProperties.FeedbackEnabled === 'true'
+class State {
```
Comment (MynockSpit) [inline lambdas/static-asset-uploader/index.js]: Why a class? (Also, make sure to run the tests. A lot of the mocking the tests were doing were based on mocking `exports.foo`.)

File: cloudformation/template.yaml [hunk 4]
```diff
@@ -126,11 +126,21 @@ Parameters:
...
 
+  LocalDevelopmentMode:
+    Type: String
+    Description: Enabling this disables CORS for easier local development. Do not enable this in production! Additionally, do not update a stack that was previously in development mode to be a production stack; instead, make a new stack that has never been in development mode.
+    Default: 'false'
+    AllowedValues: 
+      - 'false'
+      - 'true'
+    ConstraintDescription: Malformed input - Parameter LocalDevelopmentMode value must be either 'true' or 'false'
+
```
[the remark this answers is not in the document]
Comment (amazon-meaisiah) [reply cloudformation/template.yaml]: 1. `LocalDevelopmentMode` is basically the same as `DevelopmentMode` on the front end stuff (no CORS, allows localhost), but without the rest of the backend reconfiguration for development mode (S3 set to release mode, etc.).
2. Not sure, but I plan to look into it later. There's only a handful of resources `DevelopmentMode` can affect that `LocalDevelopmentMode` doesn't, and it's fairly easy to figure out which ones based on the conditions set in the template.

File: lambdas/common-layer/nodejs/node_modules/dev-portal-common/notify-cfn.js (hunk 1 above)
Comment (amazon-meaisiah) [reply lambdas/common-layer/nodejs/node_modules/dev-portal-common/notify-cfn.js]: Nope, and that's why I changed it. I'd rather have fewer ways to call it so it's fewer things we need to audit later.

File: lambdas/listener/index.js (hunk 2 above)
Comment (amazon-meaisiah) [reply lambdas/listener/index.js]: In async functions, you have to `return await` if you want the exceptions to be caught correctly in surrounding `catch` blocks.

```js
// Logs `caught!`
try {
  return await Promise.reject(new Error())
} catch (err) {
  console.log("caught!")
}

// Doesn't log anything
try {
  return Promise.reject(new Error())
} catch (err) {
  console.log("caught!")
}
```

I blame TC39 for not having `return` implicitly `await` like literally everyone else intuitively expects it to so it can trigger `catch` blocks as appropriate.

File: lambdas/static-asset-uploader/index.js (hunk 3 above)
Comment (amazon-meaisiah) [reply lambdas/static-asset-uploader/index.js]: I ran and updated the tests accordingly.

The reason I used a class was so I wasn't having to pass these two variables *everywhere* on each call. It's also easier to stub out - I can just stub out the methods without having to globally export them or restore their previous values.

File: lambdas/listener/index.js (hunk 2 above)
Comment (MynockSpit) [reply lambdas/listener/index.js]: I see. I assumed the consuming function was catching b/c this try/catch rethrows, but now I see it is not.

File: lambdas/static-asset-uploader/index.js (hunk 3 above)
Comment (MynockSpit) [reply lambdas/static-asset-uploader/index.js]: 👍

File: cloudformation/template.yaml (hunk 4 above)
[the remark this answers is not in the document]
Comment (amazon-meaisiah) [reply cloudformation/template.yaml]: FWIW, I don't want `LocalDevelopmentMode` to stick around permanently, either, if it helps. It's an ugly hack and the only reason I created it was because `DevelopmentMode` was giving me errors that didn't exist in release, but not enabling it gave me CORS issues when I was using the `localhost` dev server.

File: __tests__/cfn-integration-test.js [hunk 5]
```diff
@@ -2,111 +2,111 @@ const fs = require('fs')
...
+          ParameterValue: `integ-${stackMiddlefix}-${unixTimestamp}`
+        }
+      ],
+      // RoleARN: 'STRING_VALUE',
+      TimeoutInMinutes: cfnTimeout
+    }
 
-        logger(`verifying that stack is available at ${devPortalUrl} .`)
-        let staticIndex = await rp(devPortalUrl)
+    console.log('commonTest', region)
```
Comment (skylarbemus) [inline __tests__/cfn-integration-test.js]: I see `console.log`, `_console` and `logger` - do we need all three?

File: dev-portal/src/services/misc.js [hunk 6]
```diff
@@ -1,23 +1,23 @@
...
+      const [key, value] = param.split('=')
+      params[key] = value ? decodeURIComponent(value) : ''
+      return params
     }, {})
 }
 
-export function toTitleCase(string) {
-  let firstLetter = string[0]
-  let allOtherLetters = string.slice(1)
+export function toTitleCase (string) {
```
Comment (skylarbemus) [inline dev-portal/src/services/misc.js]: Do we need to be able to handle cases where capitalization matters? e.g. `APIs for John Doe"

File: lambdas/backend/__tests__/admin-sdk-generation-test.js [hunk 7]
```diff
@@ -1,5 +1,5 @@
-const putAdminCatalogSdkGeneration = require('../express-route-handlers').putAdminCatalogSdkGeneration
-const deleteAdminCatalogSdkGeneration = require('../express-route-handlers').deleteAdminCatalogSdkGeneration
+// const putAdminCatalogSdkGeneration = require('../express-route-handlers').putAdminCatalogSdkGeneration
```
Comment (skylarbemus) [inline lambdas/backend/__tests__/admin-sdk-generation-test.js]: Do we need to keep these imports?

File: __tests__/cfn-integration-test.js (hunk 5 above)
Comment (amazon-meaisiah) [reply __tests__/cfn-integration-test.js]: Probably not, but we can revisit it later.

File: dev-portal/src/services/misc.js (hunk 6 above)
Comment (amazon-meaisiah) [reply dev-portal/src/services/misc.js]: Probably not, but we can look into it later.

File: lambdas/backend/__tests__/admin-sdk-generation-test.js (hunk 7 above)
Comment (amazon-meaisiah) [reply lambdas/backend/__tests__/admin-sdk-generation-test.js]: Likely not, and these in particular are broken anyways. We can revisit them later, once I have the chance. (This isn't the only commented-out import, BTW.)
