### PR TITLE
Fixes for catalog updater

### LINKED ISSUE #87: Update catalog-updater to get usagePlan throttle and quota info
To be able to show limits and such on the dashboard.
- [x] Update backend model.
- [x] Update dashboard to use data.

### PR DESCRIPTION
**Pull request by Trial-In-Error**
There are several changes in this commit:

First, YAML files should be supported again in the catalog.

Second, usage plan throttle and quota information is exposed to the
front-end in the catalog. Closes #87.

Third, users can name their file API:STAGE.json or API:STAGE.yaml,
and their apiId and stageName will be extracted from the filename. An
example might be the file 'catalog/a1e3cf8aqu:production.json'. If the
file is not named in this format, we fall back to trying to extract the
apiId and stageName from the swagger's host and basePath fields. This
will fail if the api has a custom domain associated with it.

### CODE REVIEW

File: lambdas/catalog-updater/index.js [hunk 1]
```diff
@@ -26,16 +26,57 @@ function swaggerFileFilter(file) {
...
+
 
   return s3.getObject(params).promise()
-    .then((obj) => {
-      console.log(`swaggerFile: ${JSON.stringify(obj)}`)
-      return obj
+    .then((s3Repr) => {
+      let result = { body: s3Repr.Body.toString() }
+      console.log(`Processing file ${file.Key}:`)
+      console.log(`file.Key.split('catalog/').pop(): ${file.Key.split('catalog/').pop()}`)
```
Comment (Trial-In-Error) [inline lambdas/catalog-updater/index.js]: These two lines should go.

File: lambdas/catalog-updater/index.js [hunk 2]
```diff
@@ -49,40 +90,54 @@ function getSwaggerFile(file) {
...
-        console.log(`apiId: ${apiStage.apiId}`)
-        console.log(`swaggerFile.indexOf(apiStage.apiId): ${swaggerFile.indexOf(apiStage.apiId)}`)
-        return swaggerFile.indexOf(apiStage.apiId) !== -1
+    _.chain(swaggerFileReprs)
+      .find((swaggerFileRepr) => {
+        return swaggerFileRepr.apiStageKey === `${apiStage.apiId}:${apiStage.stage}`
       })
-      .tap((swaggerFile) => {
-        if(swaggerFile) {
-          api.swagger = JSON.parse(swaggerFile)
```
Comment (Trial-In-Error) [inline lambdas/catalog-updater/index.js]: This is what broke YAML support. Oops.

File: lambdas/catalog-updater/index.js [hunk 3]
```diff
@@ -49,40 +90,54 @@ function getSwaggerFile(file) {
...
+      .tap((swaggerFileRepr) => {
+        if(swaggerFileRepr) {
+          let swaggerOrError = _.attempt(JSON.parse, swaggerFileRepr.body)
+          // parse the JSON if it's JSON, otherwise, leave it as a string
+          _.isError(swaggerOrError) ? api.swagger = swaggerFileRepr.body : api.swagger = swaggerOrError
           api.id = apiStage.apiId
-          //TO-DO: Allow for customizing image?
+          api.stage = apiStage.stage
```
Comment (Trial-In-Error) [inline lambdas/catalog-updater/index.js]: We now have the apiId and stageName in the catalog!

File: lambdas/catalog-updater/index.js [hunk 4]
```diff
@@ -49,40 +90,54 @@ function getSwaggerFile(file) {
...
- * @param {Array} swaggerFiles array of swagger file bodies retrieved from s3
+ * @param {Array} swaggerFileReprs array of swagger file representations, each with a body and path parameter
  * @returns {Object} a 'catalog object' with id, name, and apis properties
  */
-function usagePlanToCatalogObject(usagePlan, swaggerFiles) {
+function usagePlanToCatalogObject(usagePlan, swaggerFileReprs) {
   let catalogObject = {
     id: usagePlan.id,
     name: usagePlan.name,
+    throttle: usagePlan.throttle,
```
Comment (Trial-In-Error) [inline lambdas/catalog-updater/index.js]: Exposes throttle and quota

File: lambdas/catalog-updater/index.js [hunk 5]
```diff
@@ -49,40 +90,54 @@ function getSwaggerFile(file) {
...
+        return swaggerFileRepr.apiStageKey === `${apiStage.apiId}:${apiStage.stage}`
       })
-      .tap((swaggerFile) => {
-        if(swaggerFile) {
-          api.swagger = JSON.parse(swaggerFile)
+      .tap((swaggerFileRepr) => {
+        if(swaggerFileRepr) {
+          let swaggerOrError = _.attempt(JSON.parse, swaggerFileRepr.body)
+          // parse the JSON if it's JSON, otherwise, leave it as a string
+          _.isError(swaggerOrError) ? api.swagger = swaggerFileRepr.body : api.swagger = swaggerOrError
```
Comment (MynockSpit) [inline lambdas/catalog-updater/index.js]: Will this mean that when it gets sent to the front end, the spec will be a YAML string? If so, there's a change or two we'll need to make on the front-end. We attempt to grab data (currently just the API Name and Version) from the (JSON) swagger doc.

Comment (Trial-In-Error) [reply lambdas/catalog-updater/index.js]: Yep. I'm not sure that we have any option other than to send it stringified? For now, we'll continue cautioning users to only use JSON (but this brings YAML support to the backend). Speaking of which, there's a README change that needs to go with this.

Comment (MynockSpit) [reply lambdas/catalog-updater/index.js]: Only other option I can think of is converting the yaml. If we did it on the server side, wouldn't need the regex's to get apiId and stageName. (Or rather, we'd need different regexes.)

Warning is good enough for me. YAML support probably isn't a big deal while we only support API Gateway Swagger.
